spring.application.name=weather-playground-test

sec=sec09

spring.sql.init.data-locations=classpath:sql/data.sql
spring.sql.init.mode=always

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/spring_webflux
spring.r2dbc.username=postgres
spring.r2dbc.password=chris

logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.postgresql.QUERY=DEBUG
logging.level.io.r2dbc.postgresql.PARAM=DEBUG
